meta_product_name: "BopNightlife"
meta_title: "BopNightlife - The after hours app"
meta_description: "The after hours app"
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
