meta_product_name: "BopNightLifee"
meta_title: "BopNightlife - We're revolutionising nigthclub tech"
meta_description: ""
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
